# Generated by Django 5.0.1 on 2024-10-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockdata',
            name='financial_d_symbol_108401_idx',
        ),
    ]
